### ISSUE TITLE
version 2.1  Unsubscribe

### ISSUE THREAD

**Issue by akeilox** [enkelmedia/NewsletterStudioContrib#1]
having issue compiling v2 example with the latest v2.1 NewsletterStudio.dll;
complains on NewsletterStudio.Bll.Providers.SubscriptionProviderBase.Unsubscribe(string, string)

Error   1   'NewsletterStudioContrib.SubscriptionProviders.TeaCommerceSubscriptionProvider' does not implement inherited abstract member 'NewsletterStudio.Bll.Providers.SubscriptionProviderBase.Unsubscribe(string, string)'  F:\NewsletterStudioContrib-master\Newsletter Studio V2\NewsletterStudioContrib\SubscriptionProviders\TeaCommerceSubscriptionProvider.cs 14  18  NewsletterStudioContrib

**Comment by enkelmedia** [comment]
Thanks =D Will update to the latest version after the summer

**Comment by holzerma** [comment]
Hi,

I want to implement a newsletter with newsletterstudio but with subscribers from an external database view. 
i still get the same problem during building this demo, is there a update available?
best

**Comment by enkelmedia** [comment]
Hi!
Just implement the members thats not implemented and you will be able to build the project.

/ m
